
services:

  database:
    image: postgres
    container_name: otp-database
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
    # - postgres_data:/var/lib/postgresql/data
    - ./database/data:/var/lib/postgresql/data
    ports:
      - "5431:5432"
    restart: no
    env_file:
      - ./.env

  frontend:
    container_name: otp-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        buildType: build-dc
    ports:
      - "80:80"
    restart: no

  backend:
    container_name: otp-backend
    depends_on:
      database:
        condition: service_started
      webrtc-server: # Add dependency on webrtc-server
        condition: service_started
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    restart: no
    env_file:
      - ./.env

  webrtc-server:
    container_name: otp-webrtc-server
    build:
      context: ./webrtc
      dockerfile: Dockerfile
    ports:
      - "5001:5000"
    restart: no
    volumes:
      - ./webrtc:/app
    environment:
      - NODE_ENV=development