package de.thu.thutorium.database.DBOMappers;

import de.thu.thutorium.api.transferObjects.common.MeetingTO;
import de.thu.thutorium.database.dbObjects.MeetingDBO;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;

/**
 * Mapper interface for converting between {@link MeetingTO} and {@link MeetingDBO}.
 *
 * <p>This interface uses MapStruct to map data transfer objects (DTOs) to database objects (DBOs)
 * and vice versa. The mapping configuration specifies how certain fields should be handled, such as
 * ignoring unmapped fields.
 *
 * <p>Annotations used:
 *
 * <ul>
 *   <li>@Mapper: Marks this interface as a MapStruct mapper.
 *   <li>componentModel = "spring": Configures the mapper to be a Spring-managed bean.
 *   <li>unmappedTargetPolicy = ReportingPolicy.IGNORE: Ignores unmapped target properties to avoid
 *       build errors.
 *   <li>@Mapping: Customizes the mapping of specific fields.
 * </ul>
 */
@Mapper(componentModel = "spring")
public interface MeetingDBMapper {

  /**
   * Maps a {@link MeetingTO} object to a {@link MeetingDBO} object.
   *
   * <p>Custom mapping configurations:
   *
   * <ul>
   *   <li>tutor: Ignored because it will be set in the service layer.
   *   <li>course: Ignored because it will be set in the service layer.
   *   <li>address: Ignored because it will be set in the service layer.
   *   <li>participants: Ignored because it is default-initialized in the constructor.
   *   <li>meetingId: Ignored because it is auto-generated by the database.
   *   <li>universityName, campusName: Ignored because they are part of address details.
   * </ul>
   *
   * @param meetingTO the {@link MeetingTO} object to map.
   * @return the mapped {@link MeetingDBO} object.
   */
  @Mapping(target = "tutor", ignore = true) // Will be set in service layer
  @Mapping(target = "course", ignore = true) // Will be set in service layer
  @Mapping(target = "address", ignore = true) // Will be set in service layer
  @Mapping(target = "participants", ignore = true) // Will be set in service layer
  @Mapping(target = "meetingId", ignore = true) // Auto-generated in the database
  @Mapping(source = "roomNum", target = "roomNum")
  @Mapping(source = "meetingDate", target = "meetingDate")
  @Mapping(source = "startTime", target = "startTime")
  @Mapping(source = "endTime", target = "endTime")
  @Mapping(source = "duration", target = "duration")
  @Mapping(source = "meetingType", target = "meetingType")
  MeetingDBO toEntity(MeetingTO meetingTO);
}
