apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: registry.digitalocean.com/thutorium-registry/backend
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: env-file-secret
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://database:5432/otpDb
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: env-file-secret
                  key: POSTGRES_USER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: env-file-secret
                  key: POSTGRES_PASSWORD
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: env-file-secret
                  key: JWT_SECRET_KEY
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: registry.digitalocean.com/thutorium-registry/frontend
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: env-file-secret
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webrtc-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webrtc-server
  template:
    metadata:
      labels:
        app: webrtc-server
    spec:
      containers:
        - name: webrtc-server
          image: registry.digitalocean.com/thutorium-registry/webrtc
          ports:
            - containerPort: 5000
          envFrom:
            - secretRef:
                name: env-file-secret
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
        - name: database
          image: postgres:latest
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: otpDb
            - name: POSTGRES_USER
              value: otp
            - name: POSTGRES_PASSWORD
              value: otp
