apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  type: ClusterIP  # Internal only
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: ClusterIP  # CHANGED: No direct LoadBalancer, handled by Ingress
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: database
spec:
  type: ClusterIP  # Internal only
  selector:
    app: database
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: webrtc-server
spec:
  type: ClusterIP  # CHANGED: No direct LoadBalancer, handled by Ingress
  selector:
    app: webrtc-server
  ports:
    - name: webrtc
      protocol: TCP
      port: 5000
      targetPort: 5000
