name: Deploy to DigitalOcean

on:
  workflow_dispatch:
  push:
    branches:
      - deploy

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to DigitalOcean Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.REGISTRY_LINK }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.DO_PAT }}

#      - name: Build and push backend Docker image
#        uses: docker/build-push-action@v4
#        with:
#          context: ./backend
#          push: true
#          tags: ${{ secrets.REGISTRY_LINK }}/backend:latest
#
#      - name: Build and push frontend Docker image
#        uses: docker/build-push-action@v4
#        with:
#          context: ./frontend
#          push: true
#          tags: ${{ secrets.REGISTRY_NAME }}/frontend:latest
#
#      - name: Build and push WebRTC server Docker image
#        uses: docker/build-push-action@v4
#        with:
#          context: ./webrtc
#          push: true
#          tags: ${{ secrets.REGISTRY_NAME }}/webrtc-server:latest

#====================================================================
      - name: Build and push backend Docker image
        run: |
          docker buildx build --push -t registry.digitalocean.com/thutorium-registry/backend ./backend

      - name: Build and push frontend Docker image
        run: |
          docker buildx build --push -t registry.digitalocean.com/thutorium-registry/frontend ./frontend

      - name: Build and push WebRTC server Docker image
        run: |
          docker buildx build --push -t registry.digitalocean.com/thutorium-registry/webrtc ./webrtc

      - name: Set up kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: 'latest'
#====================================================================
      - name: Configure kubectl with DigitalOcean
        run: doctl kubernetes cluster kubeconfig save do-fra1-k8s-thutorium
        env:
          DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DO_PAT }}

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f ./.github/k8s/deployment.yaml
          kubectl apply -f ./.github/k8s/service.yaml
