package de.thu.thutorium.model;

import com.fasterxml.jackson.annotation.JsonBackReference;
import jakarta.persistence.*;
import java.time.LocalDate;
import java.time.LocalDateTime;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Represents a course entity within the system. This entity is mapped to the {@code course} table
 * in the database.
 *
 * <p>The course is associated with a tutor (user) and belongs to a specific category. It includes
 * information such as the course name, description, start date, end date, and the timestamp of when
 * the course was created.
 *
 * <p>Lombok annotations are used to automatically generate boilerplate code like getters, setters,
 * and constructors.
 *
 * @see User
 * @see Category
 */
@Entity
@Table(name = "course")
@Data
@NoArgsConstructor
@AllArgsConstructor
public class Course {

  /**
   * The unique identifier for the course. This value is automatically generated by the database.
   */
  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  @Column(name = "course_id")
  private Long courseId;

  /**
   * The tutor responsible for teaching the course.
   *
   * <p>This relationship is mapped by the {@code tutor} field in the {@link User} entity. Deleting
   * a course does not delete the associated tutor.
   */
  @ManyToOne
  @JoinColumn(name = "tutor_id", nullable = false)
  @JsonBackReference
  private User tutor;

  /** The name of the course. This field is mandatory and cannot be null. */
  @Column(name = "course_name", nullable = false)
  private String courseName;

  /** A description of the course. This field is mandatory and cannot be null. */
  @Column(name = "description", nullable = false)
  private String description;

  /** The timestamp when the course was created. This field is mandatory and cannot be null. */
  @Column(name = "created_at", nullable = false)
  private LocalDateTime createdAt;

  /** The start date of the course. This field is optional and can be {@code null}. */
  @Column(name = "start_date")
  private LocalDate startDate;

  /** The end date of the course. This field is optional and can be {@code null}. */
  @Column(name = "end_date")
  private LocalDate endDate;

  /**
   * The category to which the course belongs. This relationship is mapped by the {@code category}
   * field in the {@link Category} entity. This field is mandatory and cannot be null.
   */
  @ManyToOne
  @JoinColumn(name = "course_category_id", nullable = false)
  private Category category;
}
